print("This program gathers 2 dates, and displays which date comes first.")
print("Gathering the first date...")
year1 = input("Enter the year: ")
month1 = input("Enter the month")
day1 = input("Enter the day: ")
print("Gathering the second date...")
year2 = input("Enter the year: ")
month2 = input("Enter the month: ")
day2 = input("Enter the day: ")
if (day2 < day1):
    print("test")
print("test")
